# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_wine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='Accept_credit_card',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='accept_android_pay',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='alcohol',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='attire',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='best_night',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='bike_parking',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='caters',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='coat_check',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='delivery',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='fri',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='gender_neutral_rooms',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='good_for',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='good_for_dancing',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='good_for_kids',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='happy_hour',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='has_pool_table',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='has_tv',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='mon',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='music',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='noise_level',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='outdoor_seating',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='parking',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='sat',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='smoking',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='sun',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='take_out',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='take_reservations',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='thu',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='tue',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='waiter_service',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='wed',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='wheelchair_accessible',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='wifi',
            field=models.CharField(default='Yes', max_length=200),
        ),
    ]
