# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20170522_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
