# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20170522_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[(1, 'red'), (2, 'green'), (3, 'blue')], max_length=200, null=True),
        ),
    ]
