# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20170523_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=200, null=True),
        ),
    ]
