# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20170523_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='name',
            new_name='title',
        ),
    ]
