# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20170524_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
